### ISSUE TITLE
Programmable Cloud Native Network Security Framework

### ISSUE THREAD

**Issue by uni2u** [uni2u/momlist#2]
# Title (need a cool name)
- 좋은 이름을 주세요
- 프레임워크로 진화는 매우 좋은 방향으로 생각하며 전적으로 동의
  - 과제에서 진행하고 있는 eBPF 기반 프로젝트 (K8s 이미지, 런타임 보안 관련) 결합 가능
  - 향후, 여러 과제에 진입하기 위한 발판으로 삼을 수 있음
  - DevSecOps 및 Zero Trust (또는 Zero Touch) 지원
- dashboard 를 위한 api 제공
  - 기존 과제에서 활용한 dashboard 에 ceno 통합

## keywords
  - Programmable, Cloud Native Network, Network Security

### [The Power of eBPF for Cloud Native Systems](https://cybersecurity-magazine.com/the-power-of-ebpf-for-cloud-native-systems/)
- ![eBPF stack](https://cybersecurity-magazine.com/wp-content/uploads/2022/12/Figure-3-1536x510.jpg)
- ![eBPF high level use cases](https://cybersecurity-magazine.com/wp-content/uploads/2022/12/Figure-4-2048x1838.jpg)
- ![Example of load balancing using eBPF in a Kubernetes cluster](https://cybersecurity-magazine.com/wp-content/uploads/2022/12/Figure-6-2048x1165.jpg)

### [Harnessing the Power of eBPF](https://prosimo.io/harnessing-the-power-of-ebpf/)
- 멀티 클라우드 네트워킹 자동화 솔루션 [prosimo](https://prosimo.io/) 의 eBPF 활용 예
  - _**Packet Decapsulation**_: eBPF/XDP 기반 UDP (VxLAN, Geneve) 캡슐화 패킷의 빠른 처리를 통한 성능 오버헤드 개선
  - _**Service Chaining**_: 수신 패킷을 커널 내부 eBPF/XDP 로 식별하여 라우팅
  - _**Network Policy**_: eBPF 를 활용한 네트워크 ACL 기반 정책 구현
  - _**Debugging and Observability**_: eBPF 를 활용한 다양한 디버깅 시나리오 수행 및 관찰 가능성 개선 후 제품화

### CENO CNI
- K8s Network plugins
  - 기본 네트워크
  - 클러스터 구성 ?
- K8s 에 녹아들어 갈 수 있도록 ?
  - yaml 지원 ?
```
...
kind: ceno
metadata:
  ...
spec:
  chainType: "Routing"
  routingSpec:
      namespace: "default"
      chainResources:
        srcNetwork: "network name"
        chainNetwork: "network name"
        dstNetwork: "network name"
...
```
  - network policy 지원 ?
    - K8s 에 지원되는 network policy 정의 및 반영
    - 더 다양하고 단단한 보안 적용 가능성?
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
        - namespaceSelector:
            matchLabels:
              project: myproject
        - podSelector:
            matchLabels:
              role: frontend
      ports:
        - protocol: TCP
          port: 6379
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
      ports:
        - protocol: TCP
          port: 5978
```

### Load Balancer
- [Writing an eBPF/XDP load-balancer in Rust](https://konghq.com/blog/writing-an-ebpf-xdp-load-balancer-in-rust)
  - Rust 에서 eBPF 컨트롤러를 생성 한 최초의 라이브러리인 [Aya](https://aya-rs.dev/book/) 의 샘플 예제
  - aya 프레임워크 기반 UDP 로드 밸런서 (Rust eBPF/XDP 프로그램) 의 예
    - [demo](https://github.com/shaneutt/ebpf-rust-udp-loadbalancer-demo)
- [loxilb](https://github.com/loxilb-io)
  - eBPF based cloud-native load-balancer for Edge|5G|IoT|XaaS

### with DPDK
- body 를 활용한 DPDK 연동
- VPP (Vector Packet Processing)
  - DPDK+VPP VS XDP+AF_XDP ???

### Service Function Chaining
- POD 로 구성된 cFW, cIPS 등으로 패킷 흐름 제어
- prosimo 의 SFC
  - 필터링 된 트래픽은 업스트림 (응용, POD, ...) 으로 전달
  - ![SFC](https://user-images.githubusercontent.com/6227506/210484024-be253438-44a0-49f1-befa-92ddb3d5e1f3.png)
  - incoming 패킷은 커널 내부에서 eBPF/XDP 로 식별되고, 이를 활용하여 라우팅

### Firewall
- [Simple XDP Firewall with Golang](https://dev.to/hbeh/simple-xdp-firewall-with-golang-1da3)
- [High Performance Geoip Blocking in eBpf with XDP](https://metin.nextc.org/posts/High_Performance_Geoip_Blocking_in_eBpf_with_XDP.html)
  - 국가IP (GeoIP) 데이터는 국가 코드에 매핑된 IP 주소 prefix 포함
```
123.123.123.0/24        US
123.123.123.123/32    DE
```
  - eBPF map 을 기반으로 한 국가IP (GeoIP) 생성
    - eBPF 의 `BPF_MAP_TYPE_LPM_TRIE` 활용 (LPM 맵 생성)
```
123.123.123.0/24        0
123.123.123.123/32    1
```
  - 비트맵 검사를 통한 국가IP 차단
```
countries  :  US  DE  XX  XX  XX  XX  XX  XX
bitmap nth :  0   1   2   3   4   5   6   7
value      :  0   1   0   0   0   0   0   0
```

### IDS (Intrusion Detection System)
- [A flow-based IDS using Machine Learning in eBPF](https://www.researchgate.net/publication/349491862_A_flow-based_IDS_using_Machine_Learning_in_eBPF)
  - 현재 eBPF 는 Firewall 또는 Denial of Service 공격 (DDoS) 에 대한 보호 등과 같은 패킷 필터링을 통한 보안에 활용
  - eBPF 에서 ML 을 활용하여 flow 기반 네트워크 침입 탐지 시스템 개발의 가능성을 보임
    - decision tree 를 사용하여 각 패킷의 악성 여부 결정
      - 네트워크 flow 의 전체 previous context 를 고려 
  - github (https://github.com/CN-TU/machine-learning-in-ebpf)

### [Kepler](https://github.com/sustainable-computing-io/kepler)
- Kepler (Kubernetes Efficient Power Level Exporter)
  - eBPF 를 사용하여 에너지 관련 시스템 통계를 조사하고 프로메테우스 메트릭으로 제공
  - eBPF를 사용하여 CPU 성능 카운터와 Linux kernel tracepoints 정보 수집
  - cgroup과 sysfs 의 이러한 데이터와 통계는 ML 모델에 입력되어 POD 의 에너지 소비 추정
